package wire

import (
	"bytes"
	"encoding/hex"
	"errors"
	"io"
	"testing"
)

func TestBoundsAndTruncation(t *testing.T) {
	for _, h := range [][]byte{{Auth, 2, 0, 1}, {Auth, 0, 0, 48}, {2, 0, 0, 0}, {9, 0, 0, 0}, {255, 0, 0, 0}} {
		r := Reader{R: bytes.NewReader(h)}
		if _, _, err := r.Read(); !errors.Is(err, ErrProtocol) {
			t.Fatalf("header %x: %v", h, err)
		}
		if cap(r.buf) != 0 {
			t.Fatal("allocated before header validation")
		}
	}
	r := Reader{R: bytes.NewReader([]byte{Auth, 0, 0, AuthSize, 1})}
	if _, _, err := r.Read(); !errors.Is(err, io.ErrUnexpectedEOF) {
		t.Fatal(err)
	}
}
func TestProofBoundToTLS(t *testing.T) {
	key := bytes.Repeat([]byte{4}, 32)
	a := bytes.Repeat([]byte{1}, 32)
	b := bytes.Repeat([]byte{2}, 32)
	p, err := AuthPayload(key, a)
	if err != nil {
		t.Fatal(err)
	}
	if !VerifyAuth(key, a, p) || VerifyAuth(key, b, p) {
		t.Fatal("exporter binding failed")
	}
	p[1] ^= 1
	if VerifyAuth(key, a, p) {
		t.Fatal("tampered nonce accepted")
	}
	for _, version := range []byte{0, 1, 2} {
		p[0] = version
		copy(p[17:], proof(key, a, p[:17]))
		if VerifyAuth(key, a, p) {
			t.Fatal("old protocol version accepted")
		}
	}
}

// Public vector from PROTOCOL.md, independently generated by the Rust peer.
func TestAuthProtocolVector(t *testing.T) {
	frame, err := hex.DecodeString("0100003103a0a1a2a3a4a5a6a7a8a9aaabacadaeaf9e1d50ff1133d04ce8400dacfaab3a595cd58deeebb918e97ea7f9b38710268b")
	if err != nil {
		t.Fatal(err)
	}
	key, exporter := make([]byte, 32), make([]byte, 32)
	for i := range key {
		key[i], exporter[i] = byte(i), byte(i+32)
	}
	r := Reader{R: bytes.NewReader(frame)}
	typ, payload, err := r.Read()
	if err != nil || typ != Auth || !VerifyAuth(key, exporter, payload) {
		t.Fatal("protocol AUTH vector rejected", err)
	}
	var encoded bytes.Buffer
	if err := Write(&encoded, Auth, payload); err != nil || !bytes.Equal(frame, encoded.Bytes()) {
		t.Fatal("protocol AUTH encoding changed", err)
	}
}

type recordingWriter struct {
	bytes.Buffer
	writes int
	short  bool
}

func (w *recordingWriter) Write(p []byte) (int, error) {
	w.writes++
	if w.short {
		return len(p) - 1, nil
	}
	return w.Buffer.Write(p)
}
func TestAuthWrite(t *testing.T) {
	auth, err := AuthPayload(make([]byte, 32), make([]byte, 32))
	if err != nil {
		t.Fatal(err)
	}
	w := new(recordingWriter)
	if err := Write(w, Auth, auth); err != nil {
		t.Fatal(err)
	}
	r := Reader{R: w}
	typ, got, err := r.Read()
	if err != nil || typ != Auth || !bytes.Equal(got, auth) || w.writes != 1 {
		t.Fatal("auth round trip", err)
	}
	if err := Write(&recordingWriter{short: true}, Auth, auth); !errors.Is(err, io.ErrShortWrite) {
		t.Fatal(err)
	}
	w = new(recordingWriter)
	if err := Write(w, Auth, auth[:48]); err == nil || w.writes != 0 {
		t.Fatal("invalid auth emitted")
	}
}

func TestAddresses(t *testing.T) {
	for _, a := range []string{"127.0.0.1:443", "[::1]:443", "example.com:443"} {
		p, e := EncodeAddress(a)
		if e != nil {
			t.Fatal(e)
		}
		got, e := DecodeAddress(p)
		if e != nil || got != a {
			t.Fatalf("%s => %s %v", a, got, e)
		}
		if _, e = DecodeAddress(append(p, 1)); e == nil {
			t.Fatal("trailing data accepted")
		}
	}
}
func FuzzRead(f *testing.F) {
	f.Add([]byte{Auth, 0, 0, AuthSize})
	f.Add([]byte{2, 0, 0, 1, 42})
	f.Fuzz(func(t *testing.T, b []byte) {
		r := Reader{R: bytes.NewReader(b)}
		_, p, _ := r.Read()
		if len(p) > AuthSize {
			t.Fatal("unbounded payload")
		}
	})
}
