PLUGIN_NAME=            veil
PLUGIN_VERSION?=        0.3.0
PLUGIN_COMMENT=         Veil SOCKS5 and HTTP proxy management
PLUGIN_MAINTAINER=      rc-chn@users.noreply.github.com
PLUGIN_LICENSE=         GPLv3
PLUGIN_WWW=             https://github.com/RC-CHN/Project-Veil

.include "../../Mk/plugins.mk"
