#!/bin/sh /etc/rc.common
# Base procd integration; UCI/LuCI presentation is a separate adapter.
START=90
STOP=10
USE_PROCD=1

start_service() {
    mkdir -p /etc/veil /var/run/veil
    chmod 0700 /etc/veil /var/run/veil
    procd_open_instance
    procd_set_param command /usr/sbin/veild \
        -state-dir /etc/veil -socket /var/run/veil/control.sock -autostart
    procd_set_param respawn 3600 5 5
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}
